### ISSUE TITLE
https://srush-minichain.hf.space/ not working

### ISSUE THREAD

**Issue by tianjianjiang** [srush/MiniChain#20]
Hi,

Really exciting to have MiniChain. It makes more sense to me for prototyping.
I really want to sell it to my colleagues, and for that it will be nice to have [MiniChain Zoo](https://srush-minichain.hf.space/) working again.
At this moment, it says
`Your space is on error, check its status on hf.co`

And I'm not sure whether https://huggingface.co/spaces/huggingface/minichain is the same thing.

🙏

**Comment by srush** [comment]
Ah, I'll fix asap.

**Comment by srush** [comment]
Fixed.

**Comment by srush** [comment]
(yes they are the same thing)
